---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtools-service-registry
spec:
  selector:
    matchLabels:
      app: webtools-service-registry
  replicas: 1
  template:
    metadata:
      labels:
        app: webtools-service-registry
    spec:
      containers:
      - name: webtools-service-registry
        image: "ikoyski/webtools-service-registry:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8188
---
apiVersion: v1
kind: Service
metadata:
  name: webtools-service-registry
spec:
  selector:
    app: webtools-service-registry
  ports:
  - protocol: "TCP"
    port: 8188
    targetPort: 8188
  type: NodePort
  