server:
  port: 8188

spring:
  application:
    name: webtools-service-registry

eureka:
  instance:
    hostname: 192.168.0.164
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
